#!/usr/bin/env bash
##############################################################################
# create-tenant.sh — Bootstrap a new tenant in the platform
#
# Usage:
#   ./infra/scripts/create-tenant.sh <slug> [--domain <domain>] [--port-offset <n>]
#
# Examples:
#   ./infra/scripts/create-tenant.sh zenco
#   ./infra/scripts/create-tenant.sh mg-masajes --domain mgmasajes.com --port-offset 2
#
# What it does:
#   1. Validates the slug (lowercase, alphanumeric + hyphens)
#   2. Creates infra/tenants/<slug>/ with a docker-compose override
#   3. Creates a .env template for the tenant
#   4. Creates clients/<slug>/ scaffold if it doesn't exist
#   5. Prints next steps for Coolify deployment
##############################################################################

set -euo pipefail

# ── Helpers ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Parse arguments ───────────────────────────────────────────────────────────
SLUG=""
CUSTOM_DOMAIN=""
PORT_OFFSET=0

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain)       CUSTOM_DOMAIN="$2"; shift 2 ;;
    --port-offset)  PORT_OFFSET="$2";   shift 2 ;;
    -*)             error "Unknown option: $1" ;;
    *)              SLUG="$1"; shift ;;
  esac
done

[[ -z "$SLUG" ]] && error "Usage: $0 <tenant-slug> [--domain <domain>] [--port-offset <n>]"

# Validate slug: lowercase letters, digits, hyphens only
if [[ ! "$SLUG" =~ ^[a-z0-9][a-z0-9-]*[a-z0-9]$ && ! "$SLUG" =~ ^[a-z0-9]$ ]]; then
  error "Slug must be lowercase alphanumeric with hyphens (e.g. 'my-tenant'). Got: '$SLUG'"
fi

# ── Derived values ────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$INFRA_DIR")"

# Convert slug to UPPER_SNAKE for env var names (zenco → ZENCO, mg-masajes → MG_MASAJES)
SLUG_UPPER="${SLUG^^}"
SLUG_UPPER="${SLUG_UPPER//-/_}"

TENANT_INFRA_DIR="$INFRA_DIR/tenants/$SLUG"
CLIENT_DIR="$REPO_ROOT/clients/$SLUG"

BACKEND_PORT=$((3000 + PORT_OFFSET))
WEB_PORT=$((8080 + PORT_OFFSET))

BASE_DOMAIN="${BASE_DOMAIN:-yourplatform.com}"
TRAEFIK_HOST="${CUSTOM_DOMAIN:-${SLUG}.${BASE_DOMAIN}}"

info "Creating tenant: $SLUG"
info "  Infra dir:    $TENANT_INFRA_DIR"
info "  Client dir:   $CLIENT_DIR"
info "  Backend port: $BACKEND_PORT"
info "  Web port:     $WEB_PORT"
info "  Public host:  $TRAEFIK_HOST"

# ── Guard: don't overwrite existing tenant ────────────────────────────────────
if [[ -d "$TENANT_INFRA_DIR" ]]; then
  warn "Tenant directory already exists: $TENANT_INFRA_DIR"
  read -r -p "Overwrite? [y/N] " CONFIRM
  [[ "$CONFIRM" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }
fi

mkdir -p "$TENANT_INFRA_DIR"

# ── 1. Generate docker-compose override ──────────────────────────────────────
info "Generating docker-compose.yml..."
sed \
  -e "s/\${TENANT}/$SLUG/g" \
  -e "s/\${TENANT_UPPER}/$SLUG_UPPER/g" \
  -e "s/\${TRAEFIK_HOST}/$TRAEFIK_HOST/g" \
  -e "s/\${BACKEND_PORT}/$BACKEND_PORT/g" \
  -e "s/\${WEB_PORT}/$WEB_PORT/g" \
  "$INFRA_DIR/docker-compose.tenant.yml" \
  > "$TENANT_INFRA_DIR/docker-compose.yml"

success "Created $TENANT_INFRA_DIR/docker-compose.yml"

# ── 2. Generate .env template for this tenant ─────────────────────────────────
info "Generating .env.template..."
cat > "$TENANT_INFRA_DIR/.env.template" <<EOF
##############################################################################
# Tenant: $SLUG
# Generated by create-tenant.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Copy to .env and fill in real values — never commit the real .env
##############################################################################

TENANT=$SLUG
NODE_ENV=production
PORT=3000
IMAGE_TAG=latest
GITHUB_ORG=your-org

# Database — use Supabase pooler URL or your managed DB
${SLUG_UPPER}_DATABASE_URL=postgresql://postgres.[project-ref]:PASSWORD@aws-0-us-east-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1

# JWT secret — openssl rand -base64 48
${SLUG_UPPER}_JWT_SECRET=

# Integrations (leave blank if not used)
${SLUG_UPPER}_GEMINI_API_KEY=
${SLUG_UPPER}_WHATSAPP_TOKEN=
${SLUG_UPPER}_WHATSAPP_PHONE_ID=

# Vite build args
VITE_TENANT=$SLUG
VITE_API_URL=https://api.${TRAEFIK_HOST}

# Traefik host
TRAEFIK_HOST=${TRAEFIK_HOST}

# Backup S3
S3_BUCKET=platform-backups-${SLUG}
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
S3_REGION=us-east-1
S3_ENDPOINT=https://s3.amazonaws.com
EOF

success "Created $TENANT_INFRA_DIR/.env.template"

# ── 3. Scaffold client app if it doesn't exist ───────────────────────────────
if [[ ! -d "$CLIENT_DIR" ]]; then
  info "Scaffolding client app at $CLIENT_DIR..."
  mkdir -p "$CLIENT_DIR/src/pages" "$CLIENT_DIR/src/components" "$CLIENT_DIR/public"

  cat > "$CLIENT_DIR/package.json" <<EOF
{
  "name": "@platform/client-${SLUG}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "test": "vitest run"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.4",
    "typescript": "^5.6.3",
    "vite": "^6.0.0"
  }
}
EOF

  cat > "$CLIENT_DIR/vite.config.ts" <<EOF
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: { port: 5173 },
})
EOF

  cat > "$CLIENT_DIR/src/App.tsx" <<EOF
export default function App() {
  return <h1>Tenant: ${SLUG}</h1>
}
EOF

  success "Scaffolded client app at $CLIENT_DIR"
else
  info "Client app already exists at $CLIENT_DIR — skipping scaffold"
fi

# ── 4. Register in tenants index ──────────────────────────────────────────────
TENANTS_INDEX="$INFRA_DIR/tenants/index.json"
if [[ ! -f "$TENANTS_INDEX" ]]; then
  echo '{"tenants":[]}' > "$TENANTS_INDEX"
fi

# Add tenant entry if not already present (requires jq)
if command -v jq &>/dev/null; then
  TMP=$(mktemp)
  jq --arg slug "$SLUG" \
     --arg host "$TRAEFIK_HOST" \
     --argjson bport "$BACKEND_PORT" \
     --argjson wport "$WEB_PORT" \
     '.tenants |= (map(select(.slug != $slug)) + [{
        "slug": $slug,
        "host": $host,
        "backendPort": $bport,
        "webPort": $wport,
        "createdAt": (now | todate)
      }])' \
     "$TENANTS_INDEX" > "$TMP" && mv "$TMP" "$TENANTS_INDEX"
  success "Registered $SLUG in $TENANTS_INDEX"
else
  warn "jq not found — skipping tenants index update. Install jq for full automation."
fi

# ── 5. Print next steps ───────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Tenant '$SLUG' created successfully!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Next steps:"
echo ""
echo "  1. Copy and fill in the env file:"
echo "       cp $TENANT_INFRA_DIR/.env.template $TENANT_INFRA_DIR/.env"
echo "       # edit $TENANT_INFRA_DIR/.env"
echo ""
echo "  2. Run Prisma migrations against the tenant DB:"
echo "       DATABASE_URL=<url> npx prisma migrate deploy --schema backend/prisma/schema.prisma"
echo ""
echo "  3. Build & push Docker images (or let CI do it):"
echo "       ./infra/scripts/deploy-tenant.sh $SLUG prod"
echo ""
echo "  4. In Coolify:"
echo "       a. Create a new Service → Docker Compose"
echo "       b. Point to: infra/tenants/$SLUG/docker-compose.yml"
echo "       c. Set environment variables from $TENANT_INFRA_DIR/.env"
echo "       d. Deploy — Coolify configures Traefik + SSL automatically"
echo ""
echo "  Public URL: https://$TRAEFIK_HOST"
echo "  API URL:    https://api.$TRAEFIK_HOST"
echo ""
